apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::721530570560:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1HDGAXTY25678
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::721530570560:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-25T23:39:02Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-25T23:39:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1426"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0ac5c211-683c-42ba-bd27-ad1415584334
